window.__ModuleLoader__.load({
  id: '@liumiya63/dsh-cyber',
  factory(require) {
    const React = require('react');
    const h = React.createElement;
    const dictionaries = {
      zh: { title:'DSH Cyber', subtitle:'安全执行工作区', dashboard:'仪表盘', assets:'资产', vulnerabilities:'漏洞', tasks:'工具任务', approvals:'审批中心', audit:'审计日志', knowledge:'知识库', chains:'攻击链', assistant:'安全助手', settings:'设置', refresh:'刷新', save:'保存', remove:'删除', empty:'暂无记录', loading:'加载中', error:'请求失败', verify:'校验完整性', run:'运行', approve:'批准', deny:'驳回', search:'搜索', disabled:'占位模块，执行器未启用', webshell:'WebShell', c2:'C2', value:'目标 / 值', type:'类型', titleField:'标题', severity:'严重程度', status:'状态', asset:'关联资产 ID', description:'说明 / 证据', recipe:'工具配方', params:'参数 JSON', mode:'智能体模式', message:'任务描述', importText:'导入文本', query:'检索词', label:'名称', from:'起点资产 ID', to:'终点资产 ID', relation:'关系', result:'结果', cancel:'取消', export:'导出 JSON', import:'导入 JSON', confirmDelete:'确认删除该记录？', low:'低', medium:'中', high:'高', critical:'严重', info:'信息', open:'待确认', confirmed:'已确认', fixed:'已修复', false_positive:'误报' },
      en: { title:'DSH Cyber', subtitle:'Security execution workspace', dashboard:'Dashboard', assets:'Assets', vulnerabilities:'Findings', tasks:'Tool tasks', approvals:'Approvals', audit:'Audit', knowledge:'Knowledge', chains:'Attack chain', assistant:'Assistant', settings:'Settings', refresh:'Refresh', save:'Save', remove:'Delete', empty:'No records', loading:'Loading', error:'Request failed', verify:'Verify integrity', run:'Run', approve:'Approve', deny:'Deny', search:'Search', disabled:'Placeholder; executor disabled', webshell:'WebShell', c2:'C2', value:'Target / value', type:'Type', titleField:'Title', severity:'Severity', status:'Status', asset:'Asset ID', description:'Description / evidence', recipe:'Recipe', params:'Parameters JSON', mode:'Agent mode', message:'Task description', importText:'Import text', query:'Search terms', label:'Name', from:'Source asset ID', to:'Destination asset ID', relation:'Relation', result:'Result', cancel:'Cancel', export:'Export JSON', import:'Import JSON', confirmDelete:'Delete this record?', low:'Low', medium:'Medium', high:'High', critical:'Critical', info:'Info', open:'Open', confirmed:'Confirmed', fixed:'Fixed', false_positive:'False positive' }
    };
    const css = `.cyber{height:100%;overflow:auto;background:var(--dsw-alias-bg-base);color:var(--dsw-alias-label-primary);font-size:14px}.cyber *{box-sizing:border-box}.cyber-wrap{max-width:1180px;margin:auto;padding:32px}.cyber-head{display:flex;justify-content:space-between;align-items:center;gap:16px;margin-bottom:24px}.cyber h1{font-size:24px;margin:0 0 6px;font-weight:650}.cyber h2{font-size:16px;margin:0 0 16px}.cyber-sub{color:var(--dsw-alias-label-secondary);font-size:13px}.cyber-tabs{display:flex;gap:6px;flex-wrap:wrap;border-bottom:1px solid var(--dsw-alias-border-l1);padding-bottom:14px;margin-bottom:24px}.cyber button,.cyber input,.cyber select,.cyber textarea{font:inherit;color:inherit;border:1px solid var(--dsw-alias-border-l1);background:var(--dsw-alias-bg-layer-1);border-radius:8px;padding:9px 12px}.cyber button{cursor:pointer}.cyber button:hover{background:var(--dsw-alias-bg-layer-2);border-color:var(--dsw-alias-border-l2)}.cyber button:focus-visible,.cyber input:focus-visible,.cyber textarea:focus-visible,.cyber select:focus-visible{outline:2px solid var(--dsw-alias-brand-primary);outline-offset:2px}.cyber button[aria-selected=true],.cyber button.primary{color:var(--dsw-alias-brand-primary);border-color:var(--dsw-alias-brand-primary)}.cyber button:disabled{opacity:.5;cursor:wait}.cyber-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:16px;margin-bottom:24px}.cyber-card{border:1px solid var(--dsw-alias-border-l1);border-radius:12px;padding:20px;background:var(--dsw-alias-bg-layer-1)}.cyber-number{font-size:32px;font-weight:600;margin:8px 0}.cyber-form{display:flex;align-items:end;gap:12px;flex-wrap:wrap;padding:20px;border:1px solid var(--dsw-alias-border-l1);border-radius:12px;margin-bottom:20px}.cyber label{display:flex;flex-direction:column;gap:7px;color:var(--dsw-alias-label-secondary);min-width:150px;flex:1}.cyber input,.cyber select{min-width:0;width:100%}.cyber textarea{width:100%;min-height:110px;resize:vertical}.cyber-wide{flex-basis:100%!important}.cyber-scroll{overflow:auto}.cyber table{width:100%;border-collapse:collapse;text-align:left}.cyber th{color:var(--dsw-alias-label-secondary);font-size:12px;font-weight:500;white-space:nowrap}.cyber td,.cyber th{padding:12px;border-bottom:1px solid var(--dsw-alias-border-l1);vertical-align:top}.cyber td{max-width:360px;overflow-wrap:anywhere}.cyber-empty{text-align:center;padding:48px;color:var(--dsw-alias-label-secondary)}.cyber-notice{border:1px solid var(--dsw-alias-border-l1);padding:12px 16px;border-radius:8px;margin-bottom:16px;overflow-wrap:anywhere}.cyber-error{color:var(--dsw-alias-state-error-primary)}.cyber pre{white-space:pre-wrap;overflow-wrap:anywhere;font-size:12px;line-height:1.7}.cyber-actions{display:flex;gap:8px;flex-wrap:wrap}.cyber svg{max-width:100%}@media(max-width:700px){.cyber-wrap{padding:18px}.cyber-head{align-items:start}.cyber-tabs{gap:4px}.cyber-tabs button{padding:7px 9px}.cyber-form label{flex-basis:100%}}`;
    return {
      inject:['slots','locale'],
      apply(ctx) {
        for(const [language, dictionary] of Object.entries(dictionaries)) ctx.effect(() => ctx.locale.register('cyber',language,dictionary));
        const t = ctx.locale.bind('cyber');
        async function api(action, payload={}) {
          const response = await fetch('/api/cyber', {method:'POST',headers:{'Content-Type':'application/json','X-Cyber-UI':'1'},body:JSON.stringify({action,...payload})});
          const body = await response.json();
          if(!response.ok || body.ok===false) throw new Error(body.error?.message || body.error || response.statusText);
          return body.value ?? body.data ?? body;
        }
        function Icon({size=20}) { return h('svg',{width:size,height:size,viewBox:'0 0 24 24',fill:'none',stroke:'currentColor',strokeWidth:1.7,'aria-hidden':true},h('path',{d:'M12 2 21 6v7c0 5-6 8-9 10-3-2-9-5-9-10V6Z'}),h('path',{d:'m9 9-3 3 3 3m6-6 3 3-3 3'})); }
        function Panel() {
          React.useSyncExternalStore(fn=>ctx.locale.subscribe(fn),()=>ctx.locale.getSnapshot());
          const [tab,setTab] = React.useState('dashboard');
          const [snapshot,setSnapshot] = React.useState({});
          const [busy,setBusy] = React.useState(false);
          const [notice,setNotice] = React.useState('');
          const [failure,setFailure] = React.useState('');
          const [answer,setAnswer] = React.useState(null);
          const [models,setModels] = React.useState([]);
          const [filter,setFilter] = React.useState('');
          const [form,setForm] = React.useState({type:'domain',severity:'medium',status:'open',params:'{}',mode:'single'});
          const alive = React.useRef(true);
          async function reload(){const data=await api('snapshot');if(alive.current)setSnapshot(data);}
          React.useEffect(()=>{alive.current=true;reload().catch(e=>setFailure(e.message));api('models').then(data=>{if(alive.current)setModels(data);}).catch(e=>setFailure(e.message));const timer=setInterval(()=>reload().catch(()=>{}),4000);return()=>{alive.current=false;clearInterval(timer);};},[]);
          async function act(action,payload={},show=false){setBusy(true);setFailure('');setNotice('');try{const result=await api(action,payload);if(alive.current){if(show)setAnswer(result);else setNotice(t('save'));await reload();}return result;}catch(e){if(alive.current)setFailure(e.message);}finally{if(alive.current)setBusy(false);}}
          function field(name,label,options,wide=false){return h('label',{key:name,className:wide?'cyber-wide':''},t(label),options?h('select',{value:form[name]||options[0],onChange:e=>setForm({...form,[name]:e.target.value})},...options.map(v=>h('option',{key:v,value:v},dictionaries.en[v]?t(v):v))):h(wide?'textarea':'input',{value:form[name]||'',onChange:e=>setForm({...form,[name]:e.target.value}),name}));}
          const button=(text,fn,primary=false)=>h('button',{type:'button',disabled:busy,onClick:fn,className:primary?'primary':''},t(text));
          function rowsTable(rows,cols,actions){const filtered=(rows||[]).filter(r=>JSON.stringify(r).toLowerCase().includes(filter.toLowerCase()));return h('div',{className:'cyber-scroll'},filtered.length?h('table',null,h('thead',null,h('tr',null,...cols.map(([key,label])=>h('th',{key},t(label))),actions?h('th',null,''):null)),h('tbody',null,...filtered.map(row=>h('tr',{key:row.id||row.seq||row.name},...cols.map(([key])=>h('td',{key},typeof row[key]==='object'?JSON.stringify(row[key]):String(row[key]??''))),actions?h('td',null,actions(row)):null)))):h('div',{className:'cyber-empty'},t('empty')));}
          function dataForm(children,onSubmit){return h('form',{className:'cyber-form',onSubmit:e=>{e.preventDefault();onSubmit();}},...children,h('button',{type:'submit',disabled:busy,className:'primary'},t('save')));}
          let content;
          if(tab==='dashboard') content=h(React.Fragment,null,h('div',{className:'cyber-grid'},...['assets','vulnerabilities','tasks','approvals'].map(key=>h('div',{key,className:'cyber-card'},h('span',{className:'cyber-sub'},t(key)),h('div',{className:'cyber-number'},snapshot[key]?.length||0)))),h('div',{className:'cyber-card'},h('h2',null,t('tasks')),rowsTable(snapshot.tasks,[['id','label'],['recipe','recipe'],['status','status']])));
          if(tab==='assets') content=h(React.Fragment,null,dataForm([field('type','type',['domain','ip','port','service']),field('value','value')],()=>act('asset.create',{type:form.type,value:form.value})),h('div',{className:'cyber-actions'},button('export',()=>{const blob=new Blob([JSON.stringify(snapshot.assets||[],null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='cyber-assets.json';a.click();URL.revokeObjectURL(url);})),rowsTable(snapshot.assets,[['id','label'],['type','type'],['value','value']],row=>button('remove',()=>{if(window.confirm(t('confirmDelete')))act('asset.delete',{id:row.id});})));
          if(tab==='vulnerabilities') content=h(React.Fragment,null,dataForm([field('title','titleField'),field('severity','severity',['critical','high','medium','low','info']),field('assetId','asset'),field('description','description',null,true)],()=>act('vulnerability.create',{title:form.title,severity:form.severity,assetId:form.assetId?Number(form.assetId):undefined,description:form.description})),rowsTable(snapshot.vulnerabilities,[['id','label'],['title','titleField'],['severity','severity'],['status','status']],row=>h('select',{'aria-label':t('status'),value:row.status,onChange:e=>act('vulnerability.update',{id:row.id,status:e.target.value})},...['open','confirmed','fixed','false_positive'].map(s=>h('option',{key:s,value:s},t(s))))));
          if(tab==='tasks') content=h(React.Fragment,null,dataForm([field('recipe','recipe',(snapshot.recipes||[]).map(r=>r.name)),field('params','params',null,true)],()=>{try{act('task.run',{recipe:form.recipe||snapshot.recipes?.[0]?.name,params:JSON.parse(form.params)});}catch(e){setFailure(e.message);}}),rowsTable(snapshot.tasks,[['id','label'],['recipe','recipe'],['status','status']],row=>h('div',{className:'cyber-actions'},button('result',()=>setAnswer(row)),row.status==='running'?button('cancel',()=>act('task.cancel',{id:row.id})):null)));
          if(tab==='approvals') content=rowsTable(snapshot.approvals,[['id','label'],['recipe','recipe'],['status','status'],['params','params']],row=>row.status==='pending'?h('div',{className:'cyber-actions'},button('approve',()=>act('approval.decide',{id:row.id,approved:true})),button('deny',()=>act('approval.decide',{id:row.id,approved:false}))):null);
          if(tab==='audit') content=h(React.Fragment,null,button('verify',()=>act('audit.verify',{},true)),rowsTable(snapshot.audit,[['seq','label'],['timestamp','status'],['action','type'],['hash','value']]));
          if(tab==='knowledge') content=h(React.Fragment,null,dataForm([field('title','titleField'),field('text','importText',null,true)],()=>act('knowledge.ingest',{title:form.title,text:form.text})),h('div',{className:'cyber-form'},field('query','query'),button('search',()=>act('knowledge.search',{query:form.query},true))),rowsTable(snapshot.knowledge,[['id','label'],['title','titleField']]));
          if(tab==='chains') content=h(React.Fragment,null,dataForm([field('from','from'),field('to','to'),field('label','relation')],()=>act('chain.create',{from:Number(form.from),to:Number(form.to),label:form.label})),h('div',{className:'cyber-card'},h('svg',{viewBox:`0 0 900 ${Math.max(120,(snapshot.chains||[]).length*70)}`,role:'img','aria-label':t('chains')},...(snapshot.chains||[]).map((edge,i)=>h('g',{key:edge.id,transform:`translate(0,${i*70})`},h('rect',{x:15,y:15,width:220,height:42,rx:8,fill:'var(--dsw-alias-bg-layer-2)',stroke:'var(--dsw-alias-border-l2)'}),h('text',{x:30,y:42,fill:'var(--dsw-alias-label-primary)'},String(edge.from)),h('path',{d:'M235 36H640l-12-7m12 7-12 7',fill:'none',stroke:'var(--dsw-alias-brand-primary)'}),h('text',{x:300,y:29,fill:'var(--dsw-alias-label-secondary)'},edge.label),h('rect',{x:645,y:15,width:220,height:42,rx:8,fill:'var(--dsw-alias-bg-layer-2)',stroke:'var(--dsw-alias-border-l2)'}),h('text',{x:660,y:42,fill:'var(--dsw-alias-label-primary)'},String(edge.to)))))));
          if(tab==='assistant') content=h(React.Fragment,null,dataForm([h('label',{key:'model'},'DSH Model',h('select',{value:form.modelRoute||'',onChange:e=>setForm({...form,modelRoute:e.target.value})},h('option',{value:''},'Select model'),...models.map(m=>h('option',{key:m.provider+'/'+m.model,value:JSON.stringify([m.provider,m.model])},m.name)))),field('mode','mode',['single','plan-execute','deep','supervisor']),field('message','message',null,true)],()=>{try{const [provider,model]=JSON.parse(form.modelRoute||'[]');act('agent.run',{mode:form.mode,message:form.message,provider,model},true);}catch(e){setFailure(e.message);}}));
          if(tab==='settings') content=h('div',{className:'cyber-card'},h('h2',null,t('settings')),h('p',{className:'cyber-sub'},'DSH profile / SQLite / YAML / SHA-256'),h('p',null,t('webshell')+' — '+t('disabled')),h('p',null,t('c2')+' — '+t('disabled')));
          return h('section',{className:'cyber','aria-label':t('title')},h('style',null,css),h('div',{className:'cyber-wrap'},h('header',{className:'cyber-head'},h('div',null,h('h1',null,t('title')),h('div',{className:'cyber-sub'},t('subtitle'))),button('refresh',()=>act('snapshot'))),h('nav',{className:'cyber-tabs',role:'tablist'},...['dashboard','assistant','assets','vulnerabilities','tasks','chains','knowledge','approvals','audit','settings'].map(key=>h('button',{key,role:'tab','aria-selected':tab===key,onClick:()=>{setTab(key);setAnswer(null);setFilter('');}},t(key)))),failure?h('div',{className:'cyber-notice cyber-error',role:'alert'},failure):null,notice?h('div',{className:'cyber-notice',role:'status'},notice):null,tab!=='settings'&&tab!=='assistant'?h('input',{'aria-label':t('search'),placeholder:t('search'),value:filter,onChange:e=>setFilter(e.target.value),style:{marginBottom:16,maxWidth:320}}):null,h('div',{role:'tabpanel'},content),answer?h('div',{className:'cyber-card',style:{marginTop:20}},h('div',{className:'cyber-head'},h('h2',null,t('result')),button('cancel',()=>setAnswer(null))),h('pre',null,JSON.stringify(answer,null,2))):null));
        }
        ctx.slots.inject('sidebar.panellist',()=>ctx.slots.register({name:'sidebar.panellist',id:'cyber',order:35,label:()=>t('title')},Icon));
        ctx.slots.inject('main',()=>ctx.slots.register({name:'main',key:'cyber'},Panel));
      }
    };
  }
});
