window.__ModuleLoader__.load({
  id: '@liumiya63/dsh-cyber',
  factory(require) {
    const React = require('react');
    const h = React.createElement;
    const dictionaries = {
      zh: { title:'DSH Cyber', subtitle:'安全执行工作区', dashboard:'仪表盘', assets:'资产', vulnerabilities:'漏洞', tasks:'工具任务', approvals:'审批中心', audit:'审计日志', knowledge:'知识库', chains:'攻击链', settings:'设置', refresh:'刷新', save:'保存', remove:'删除', empty:'暂无记录', loading:'加载中', error:'请求失败', verify:'校验完整性', run:'运行', approve:'批准', deny:'驳回', search:'搜索', disabled:'占位模块，执行器未启用', webshell:'WebShell', c2:'C2', value:'目标 / 值', type:'类型', titleField:'标题', severity:'严重程度', status:'状态', asset:'关联资产 ID', description:'说明 / 证据', recipe:'工具配方', params:'参数 JSON', mode:'智能体模式', message:'任务描述', importText:'导入文本', query:'检索词', label:'名称', from:'起点资产 ID', to:'终点资产 ID', relation:'关系', result:'结果', cancel:'取消', export:'导出 JSON', import:'导入 JSON', confirmDelete:'确认删除该记录？', low:'低', medium:'中', high:'高', critical:'严重', info:'信息', open:'待确认', confirmed:'已确认', fixed:'已修复', false_positive:'误报' },
      en: { title:'DSH Cyber', subtitle:'Security execution workspace', dashboard:'Dashboard', assets:'Assets', vulnerabilities:'Findings', tasks:'Tool tasks', approvals:'Approvals', audit:'Audit', knowledge:'Knowledge', chains:'Attack chain', settings:'Settings', refresh:'Refresh', save:'Save', remove:'Delete', empty:'No records', loading:'Loading', error:'Request failed', verify:'Verify integrity', run:'Run', approve:'Approve', deny:'Deny', search:'Search', disabled:'Placeholder; executor disabled', webshell:'WebShell', c2:'C2', value:'Target / value', type:'Type', titleField:'Title', severity:'Severity', status:'Status', asset:'Asset ID', description:'Description / evidence', recipe:'Recipe', params:'Parameters JSON', mode:'Agent mode', message:'Task description', importText:'Import text', query:'Search terms', label:'Name', from:'Source asset ID', to:'Destination asset ID', relation:'Relation', result:'Result', cancel:'Cancel', export:'Export JSON', import:'Import JSON', confirmDelete:'Delete this record?', low:'Low', medium:'Medium', high:'High', critical:'Critical', info:'Info', open:'Open', confirmed:'Confirmed', fixed:'Fixed', false_positive:'False positive' }
    };
    Object.assign(dictionaries.zh, { exploration:'探索', goals:'目标', intents:'意图', facts:'事实', findings:'发现', edges:'关系', goal:'目标', intent:'意图', fact:'事实', finding:'发现', edge:'关系', objective:'目标说明', target:'目标对象', sourceId:'来源 UID', intentId:'意图 UID', affectedAssetId:'影响资产 UID（可选）', parentId:'父资产 UID（可选）', targetId:'终点 UID', kind:'关系 / 事实类型', detail:'详情', confidence:'置信度（0–1）', reproducibleSteps:'复现步骤（每行一步）', meta:'资产元信息', authorization:'授权范围', domainRecords:'领域记录', legacyRecords:'已有记录', pending:'待审批', approved:'已批准', rejected:'已驳回', running:'运行中', queued:'排队中', completed:'已完成', failed:'失败', cancelled:'已取消', interrupted:'已中断', succeeded:'成功', waiting_approval:'等待审批', ready:'已同步', syncing:'同步中', total:'总计', verified:'完整性校验通过', damaged:'完整性校验失败', unchecked:'尚未校验', brokenAt:'损坏序号', anchor:'外部锚定', notAnchored:'未外部锚定；校验仅覆盖本地哈希链', auditHelp:'检查记录顺序、前序哈希与 SHA-256 摘要。', approvalHelp:'审批仅由用户操作；请检查配方、风险与参数后决定。', risk:'风险级别', taskId:'任务 ID', timestamp:'时间', actor:'操作者', prev_hash:'前序哈希', hash:'当前哈希', action:'动作', all:'全部', noMatches:'没有匹配记录，请调整检索词。', emptyHint:'添加记录后将在这里显示。', noGraph:'暂无图谱节点，先在探索中添加目标或资产。', graphHint:'节点来自领域记录及已有资产；连线来自实际关系记录。点击节点查看完整证据。', unresolved:'未解析端点', selectReference:'请选择记录', none:'不关联', graphUnavailable:'当前快照未提供领域数据', saved:'操作完成', connection:'连接状态', severityChart:'严重程度分布', node:'节点', link:'连线', inspection:'证据详情', approvalDecision:'确认对这条任务作出审批决定？', settingsHelp:'执行能力以当前服务配置为准。' });
    Object.assign(dictionaries.en, { exploration:'Exploration', goals:'Goals', intents:'Intents', facts:'Facts', findings:'Findings', edges:'Edges', goal:'Goal', intent:'Intent', fact:'Fact', finding:'Finding', edge:'Edge', objective:'Objective', target:'Target', sourceId:'Source UID', intentId:'Intent UID', affectedAssetId:'Affected asset UID (optional)', parentId:'Parent asset UID (optional)', targetId:'Destination UID', kind:'Relationship / fact kind', detail:'Detail', confidence:'Confidence (0–1)', reproducibleSteps:'Reproduction steps (one per line)', meta:'Asset metadata', authorization:'Authorization scope', domainRecords:'Domain records', legacyRecords:'Existing records', pending:'Pending', approved:'Approved', rejected:'Rejected', running:'Running', queued:'Queued', completed:'Completed', failed:'Failed', cancelled:'Cancelled', interrupted:'Interrupted', succeeded:'Succeeded', waiting_approval:'Awaiting approval', ready:'Synced', syncing:'Syncing', total:'Total', verified:'Integrity verified', damaged:'Integrity verification failed', unchecked:'Not verified', brokenAt:'Broken at', anchor:'External anchor', notAnchored:'Not externally anchored; verification covers the local hash chain only', auditHelp:'Check sequence, previous hashes and SHA-256 digests.', approvalHelp:'Only users decide approvals. Review recipe, risk and parameters first.', risk:'Risk level', taskId:'Task ID', timestamp:'Time', actor:'Actor', prev_hash:'Previous hash', hash:'Current hash', action:'Action', all:'All', noMatches:'No matches. Adjust your search.', emptyHint:'New records will appear here.', noGraph:'No graph nodes yet. Add a goal or asset in Exploration.', graphHint:'Nodes use domain records and existing assets; links use actual relationship records. Select a node to inspect evidence.', unresolved:'Unresolved endpoints', selectReference:'Select a record', none:'No relationship', graphUnavailable:'This snapshot does not contain domain data', saved:'Operation completed', connection:'Connection', severityChart:'Severity distribution', node:'Nodes', link:'Links', inspection:'Evidence details', approvalDecision:'Confirm this approval decision?', settingsHelp:'Execution capabilities depend on current service configuration.' });
    delete dictionaries.zh.assistant;
    delete dictionaries.en.assistant;
    const css = `.cyber{height:100%;overflow:auto;background:var(--dsw-alias-bg-base);color:var(--dsw-alias-label-primary);font-size:14px}.cyber *{box-sizing:border-box}.cyber-wrap{max-width:1180px;margin:auto;padding:32px}.cyber-head{display:flex;justify-content:space-between;align-items:center;gap:16px;margin-bottom:24px}.cyber h1{font-size:24px;margin:0 0 6px;font-weight:650}.cyber h2{font-size:16px;margin:0 0 16px}.cyber-sub{color:var(--dsw-alias-label-secondary);font-size:13px}.cyber-tabs{display:flex;gap:6px;flex-wrap:wrap;border-bottom:1px solid var(--dsw-alias-border-l1);padding-bottom:14px;margin-bottom:24px}.cyber button,.cyber input,.cyber select,.cyber textarea{font:inherit;color:inherit;border:1px solid var(--dsw-alias-border-l1);background:var(--dsw-alias-bg-layer-1);border-radius:8px;padding:9px 12px}.cyber button{cursor:pointer}.cyber button:hover{background:var(--dsw-alias-bg-layer-2);border-color:var(--dsw-alias-border-l2)}.cyber button:focus-visible,.cyber input:focus-visible,.cyber textarea:focus-visible,.cyber select:focus-visible{outline:2px solid var(--dsw-alias-brand-primary);outline-offset:2px}.cyber button[aria-selected=true],.cyber button.primary{color:var(--dsw-alias-brand-primary);border-color:var(--dsw-alias-brand-primary)}.cyber button:disabled{opacity:.5;cursor:wait}.cyber-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:16px;margin-bottom:24px}.cyber-card{border:1px solid var(--dsw-alias-border-l1);border-radius:12px;padding:20px;background:var(--dsw-alias-bg-layer-1)}.cyber-number{font-size:32px;font-weight:600;margin:8px 0}.cyber-form{display:flex;align-items:end;gap:12px;flex-wrap:wrap;padding:20px;border:1px solid var(--dsw-alias-border-l1);border-radius:12px;margin-bottom:20px}.cyber label{display:flex;flex-direction:column;gap:7px;color:var(--dsw-alias-label-secondary);min-width:150px;flex:1}.cyber input,.cyber select{min-width:0;width:100%}.cyber textarea{width:100%;min-height:110px;resize:vertical}.cyber-wide{flex-basis:100%!important}.cyber-scroll{overflow:auto}.cyber table{width:100%;border-collapse:collapse;text-align:left}.cyber th{color:var(--dsw-alias-label-secondary);font-size:12px;font-weight:500;white-space:nowrap}.cyber td,.cyber th{padding:12px;border-bottom:1px solid var(--dsw-alias-border-l1);vertical-align:top}.cyber td{max-width:360px;overflow-wrap:anywhere}.cyber-empty{text-align:center;padding:48px;color:var(--dsw-alias-label-secondary)}.cyber-notice{border:1px solid var(--dsw-alias-border-l1);padding:12px 16px;border-radius:8px;margin-bottom:16px;overflow-wrap:anywhere}.cyber-error{color:var(--dsw-alias-state-error-primary)}.cyber pre{white-space:pre-wrap;overflow-wrap:anywhere;font-size:12px;line-height:1.7}.cyber-actions{display:flex;gap:8px;flex-wrap:wrap}.cyber svg{max-width:100%}@media(max-width:700px){.cyber-wrap{padding:18px}.cyber-head{align-items:start}.cyber-tabs{gap:4px}.cyber-tabs button{padding:7px 9px}.cyber-form label{flex-basis:100%}}`;
    const extraCss = `.cyber{--cyber-ok:var(--dsw-alias-state-success-primary);--cyber-warn:var(--dsw-alias-state-warn-primary)}.cyber-wrap{max-width:1440px}.cyber-card{box-shadow:0 4px 16px color-mix(in srgb,var(--dsw-alias-border-l1) 25%,transparent)}.cyber-badge{display:inline-flex;gap:6px;align-items:center;border:1px solid currentColor;border-radius:999px;padding:3px 9px;font-size:12px;white-space:nowrap;color:var(--dsw-alias-label-secondary)}.cyber-badge.success{color:var(--cyber-ok)}.cyber-badge.warn{color:var(--cyber-warn)}.cyber-badge.error{color:var(--dsw-alias-state-error-primary)}.cyber-badge.brand{color:var(--dsw-alias-brand-primary)}.cyber-split{display:grid;grid-template-columns:minmax(0,1.4fr) minmax(0,1fr);gap:20px;margin-bottom:20px}.cyber-stack{display:grid;gap:16px}.cyber-card h2{display:flex;align-items:center;justify-content:space-between;gap:12px}.cyber-bar-row{display:grid;grid-template-columns:90px 1fr 36px;gap:12px;align-items:center;margin:15px 0}.cyber-track{height:10px;border-radius:20px;background:var(--dsw-alias-bg-layer-2);overflow:hidden}.cyber-fill{height:100%;min-width:0;background:var(--dsw-alias-brand-primary);border-radius:20px}.cyber-fill.critical,.cyber-fill.high{background:var(--dsw-alias-state-error-primary)}.cyber-fill.medium{background:var(--cyber-warn)}.cyber-fill.low{background:var(--cyber-ok)}.cyber-form{background:var(--dsw-alias-bg-layer-1)}.cyber-empty{border:1px dashed var(--dsw-alias-border-l2);border-radius:12px}.cyber-tabs{overflow-x:auto;flex-wrap:nowrap}.cyber-tabs button{white-space:nowrap}.cyber graph{display:block}.cyber-graph{overflow:auto;border-radius:12px;background:var(--dsw-alias-bg-base)}.cyber-graph svg{display:block;min-width:800px;width:100%}.cyber-node{cursor:pointer}.cyber-node:hover rect,.cyber-node:focus rect{stroke:var(--dsw-alias-brand-primary);stroke-width:3}.cyber-node:focus{outline:none}.cyber-uid{font-family:monospace;font-size:12px;color:var(--dsw-alias-label-secondary)}.cyber-details{margin-top:16px}.cyber details summary{cursor:pointer;padding:10px 0}.cyber-notice.success{color:var(--cyber-ok)}.cyber-toolbar{display:flex;gap:12px;align-items:center;flex-wrap:wrap;margin-bottom:18px}.cyber-help{line-height:1.6;color:var(--dsw-alias-label-secondary)}.cyber-table-caption{text-align:left;padding:8px 12px;color:var(--dsw-alias-label-secondary)}@media(max-width:850px){.cyber-split{grid-template-columns:1fr}.cyber-wrap{padding:16px}.cyber-head{flex-wrap:wrap}.cyber-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.cyber-card{padding:16px}}@media(prefers-reduced-motion:reduce){.cyber *{scroll-behavior:auto}}`;
    return {
      inject:['slots','locale'],
      apply(ctx) {
        for(const [language, dictionary] of Object.entries(dictionaries)) ctx.effect(() => ctx.locale.register('cyber',language,dictionary));
        const t = ctx.locale.bind('cyber');
        async function api(action, payload={}) {
          const response = await fetch('/api/cyber', {method:'POST',headers:{'Content-Type':'application/json','X-Cyber-UI':'1'},body:JSON.stringify({action,...payload})});
          const body = await response.json();
          if(!response.ok || body.ok===false) throw new Error(body.error?.message || body.error || response.statusText);
          return body.value ?? body.data ?? body;
        }
        function Icon({size=20}) { return h('svg',{width:size,height:size,viewBox:'0 0 24 24',fill:'none',stroke:'currentColor',strokeWidth:1.7,'aria-hidden':true},h('path',{d:'M12 2 21 6v7c0 5-6 8-9 10-3-2-9-5-9-10V6Z'}),h('path',{d:'m9 9-3 3 3 3m6-6 3 3-3 3'})); }
        function Panel() {
          React.useSyncExternalStore(fn=>ctx.locale.subscribe(fn),()=>ctx.locale.getSnapshot());
          const [tab,setTab] = React.useState('dashboard');
          const [snapshot,setSnapshot] = React.useState({});
          const [busy,setBusy] = React.useState(false);
          const [notice,setNotice] = React.useState('');
          const [failure,setFailure] = React.useState('');
          const [answer,setAnswer] = React.useState(null);
          const [filter,setFilter] = React.useState('');
          const [form,setForm] = React.useState({type:'domain',severity:'medium',status:'open',params:'{}'});
          const [entity,setEntity] = React.useState('goal');
          const [graphForm,setGraphForm] = React.useState({confidence:'0.5',severity:'medium',type:'domain',kind:'info'});
          const [verification,setVerification] = React.useState(null);
          const [selectedNode,setSelectedNode] = React.useState(null);
          const [loaded,setLoaded] = React.useState(false);
          const graph = snapshot.graph || {};
          const graphRows = key => Array.isArray(graph[key]) ? graph[key] : [];
          const domainKinds = ['goal','intent','fact','finding','asset'];
          const domainKey = kind => kind==='asset'?'assets':`${kind}s`;
          const domainNodes = domainKinds.flatMap(kind=>graphRows(domainKey(kind)).filter(r=>typeof r.uid==='string'&&r.data&&typeof r.data==='object').map(r=>({...r,nodeKind:kind})));
          const severities = ['critical','high','medium','low','info'];
          const alive = React.useRef(true);
          async function reload(){const data=await api('snapshot');if(alive.current){setSnapshot(data);setLoaded(true);}}
          React.useEffect(()=>{alive.current=true;reload().catch(e=>setFailure(e.message));const timer=setInterval(()=>reload().catch(()=>{}),4000);return()=>{alive.current=false;clearInterval(timer);};},[]);
          async function act(action,payload={},show=false){setBusy(true);setFailure('');setNotice('');try{const result=await api(action,payload);if(alive.current){if(show)setAnswer(result);else setNotice(t('saved'));await reload();}return result;}catch(e){if(alive.current)setFailure(e.message);}finally{if(alive.current)setBusy(false);}}
          function field(name,label,options,wide=false){return h('label',{key:name,className:wide?'cyber-wide':''},t(label),options?h('select',{value:form[name]||options[0],onChange:e=>setForm({...form,[name]:e.target.value})},...options.map(v=>h('option',{key:v,value:v},dictionaries.en[v]?t(v):v))):h(wide?'textarea':'input',{value:form[name]||'',onChange:e=>setForm({...form,[name]:e.target.value}),name}));}
          const button=(text,fn,primary=false)=>h('button',{type:'button',disabled:busy,onClick:fn,className:primary?'primary':''},t(text));
          function rowsTable(rows,cols,actions){const filtered=(rows||[]).filter(r=>JSON.stringify(r).toLowerCase().includes(filter.toLowerCase()));return h('div',{className:'cyber-scroll'},filtered.length?h('table',null,h('thead',null,h('tr',null,...cols.map(([key,label])=>h('th',{key,scope:'col'},t(label))),actions?h('th',null,''):null)),h('tbody',null,...filtered.map(row=>h('tr',{key:row.uid||row.id||row.seq||row.name},...cols.map(([key])=>h('td',{key},typeof row[key]==='object'?JSON.stringify(row[key]):['severity','status','risk_level'].includes(key)?badge(row[key]):String(row[key]??''))),actions?h('td',null,actions(row)):null)))):h('div',{className:'cyber-empty'},t('empty')));}
          function dataForm(children,onSubmit){return h('form',{className:'cyber-form',onSubmit:e=>{e.preventDefault();onSubmit();}},...children,h('button',{type:'submit',disabled:busy,className:'primary'},t('save')));}
          function badge(value){const tone= ['approved','completed','succeeded','fixed','ready'].includes(value)?'success':['pending','queued','running','waiting_approval','medium','interrupted'].includes(value)?'warn':['critical','high','failed','rejected','damaged'].includes(value)?'error':'brand';return h('span',{className:`cyber-badge ${tone}`},dictionaries.en[value]?t(value):String(value||'—'));}
          function empty(message='empty'){return h('div',{className:'cyber-empty'},h('strong',null,t(message)),h('p',null,t('emptyHint')));}
          function severityChart(){const records=[...(snapshot.vulnerabilities||[]),...graphRows('findings').map(r=>r.data||{})];const counts=severities.map(s=>records.filter(r=>r.severity===s).length);const max=Math.max(1,...counts);return h('div',{className:'cyber-card'},h('h2',null,t('severityChart'),badge(String(records.length))),...severities.map((s,i)=>h('div',{key:s,className:'cyber-bar-row'},badge(s),h('div',{className:'cyber-track',role:'meter','aria-label':t(s),'aria-valuenow':counts[i],'aria-valuemin':0,'aria-valuemax':max},h('div',{className:`cyber-fill ${s}`,style:{width:`${counts[i]/max*100}%`}})),h('span',null,counts[i]))));}
          function graphView(){
            const nodes=[...domainNodes,...(snapshot.assets||[]).map(r=>({uid:`legacy-asset-${r.id}`,nodeKind:'asset',data:r,legacy:true}))];
            const positions=new Map();const groups=['goal','intent','fact','finding','asset'];let maxRows=1;
            groups.forEach((kind,col)=>{const list=nodes.filter(n=>n.nodeKind===kind);maxRows=Math.max(maxRows,list.length);list.forEach((n,index)=>positions.set(n.uid,{x:20+col*235,y:52+index*100}));});
            const edges=[...graphRows('edges').map(e=>({uid:e.uid,...e.data})),...(snapshot.chains||[]).map(e=>({uid:`legacy-edge-${e.id}`,sourceId:`legacy-asset-${e.from}`,targetId:`legacy-asset-${e.to}`,kind:e.label}))];
            const valid=edges.filter(e=>positions.has(e.sourceId)&&positions.has(e.targetId));const missing=edges.length-valid.length;
            if(!nodes.length)return empty('noGraph');
            const height=Math.max(240,maxRows*100+90);
            return h('div',{className:'cyber-card'},h('h2',null,t('chains'),h('span',{className:'cyber-actions'},badge(`${nodes.length} ${t('node')}`),badge(`${valid.length} ${t('link')}`))),h('p',{className:'cyber-help'},t('graphHint')),missing?h('p',{role:'status',className:'cyber-help'},`${t('unresolved')}: ${missing}`):null,h('div',{className:'cyber-graph'},h('svg',{viewBox:`0 0 1200 ${height}`,role:'img','aria-label':t('chains')},h('title',null,t('chains')),h('desc',null,t('graphHint')),h('defs',null,h('marker',{id:'cyber-arrow',viewBox:'0 0 10 10',refX:9,refY:5,markerWidth:6,markerHeight:6,orient:'auto-start-reverse'},h('path',{d:'M0 0L10 5L0 10Z',fill:'var(--dsw-alias-brand-primary)'}))),...groups.map((kind,i)=>h('text',{key:kind,x:20+i*235,y:25,fill:'var(--dsw-alias-label-secondary)',fontSize:13},t(domainKey(kind)))),...valid.map((e,i)=>{const a=positions.get(e.sourceId),b=positions.get(e.targetId);const same=a.x===b.x;const sx=same?a.x+200:a.x+200,sy=a.y+30,tx=same?b.x+200:b.x,ty=b.y+30;const curve=same?`M${sx} ${sy} C${sx+60} ${sy} ${tx+60} ${ty} ${tx} ${ty}`:`M${sx} ${sy} C${sx+35} ${sy} ${tx-35} ${ty} ${tx} ${ty}`;return h('g',{key:e.uid||i},h('path',{d:curve,fill:'none',stroke:'var(--dsw-alias-brand-primary)',strokeWidth:1.6,opacity:.7,markerEnd:'url(#cyber-arrow)'},h('title',null,`${e.sourceId} → ${e.targetId}: ${e.kind}`)),h('text',{x:same?sx+20:(sx+tx)/2,y:(sy+ty)/2-7,fontSize:10,fill:'var(--dsw-alias-label-secondary)'},String(e.kind||'')));}),...nodes.map(n=>{const p=positions.get(n.uid);const label=String(n.data.title||n.data.target||n.data.value||n.data.detail||n.uid);return h('g',{key:n.uid,className:'cyber-node',transform:`translate(${p.x},${p.y})`,role:'button',tabIndex:0,'aria-label':`${t(n.nodeKind)}: ${label}`,onClick:()=>setSelectedNode(n),onKeyDown:e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();setSelectedNode(n);}}},h('title',null,`${n.uid}\n${label}`),h('rect',{width:200,height:64,rx:10,fill:'var(--dsw-alias-bg-layer-1)',stroke:'var(--dsw-alias-border-l2)'}),h('text',{x:12,y:25,fontSize:13,fill:'var(--dsw-alias-label-primary)'},label.length>23?label.slice(0,22)+'…':label),h('text',{x:12,y:46,fontSize:10,fill:'var(--dsw-alias-label-secondary)'},n.uid.slice(0,26)));}))),selectedNode?h('div',{className:'cyber-details'},h('h2',null,t('inspection'),button('cancel',()=>setSelectedNode(null))),h('pre',null,JSON.stringify(selectedNode,null,2))):null);
          }
          function exploration(){
            const definitions={goal:[['target'],['objective',true],['authorization',true]],intent:[['sourceId',false,['goal','fact']],['title'],['detail',true]],fact:[['intentId',false,['intent']],['kind',false,null,['port','service','http','info','vuln']],['target'],['detail',true],['confidence']],finding:[['intentId',false,['intent']],['title'],['severity',false,null,severities],['description',true],['reproducibleSteps',true],['affectedAssetId',false,['asset'],null,true]],asset:[['type',false,null,['domain','root-domain','subdomain','ip','port','service','app','endpoint']],['value'],['meta',true],['parentId',false,['asset'],null,true]],edge:[['sourceId',false,domainKinds],['targetId',false,domainKinds],['kind',false,null,['spawns','yields','derived_from','proves','parent','affects','related']]]};
            const inputs=definitions[entity].map(([name,wide,refs,choices,optional])=>{const candidates=refs?domainNodes.filter(n=>refs.includes(n.nodeKind)):[];const props={name,value:graphForm[name]??'',onChange:e=>setGraphForm({...graphForm,[name]:e.target.value}),required:!optional&&!['authorization','detail','target','meta'].includes(name)};if(name==='target'&&entity==='goal')props.required=true;return h('label',{key:name,className:wide?'cyber-wide':''},t(name==='title'?'titleField':name),refs?h('select',props,h('option',{value:''},t(optional?'none':'selectReference')),...candidates.map(n=>h('option',{key:n.uid,value:n.uid},`${n.data.title||n.data.target||n.data.value||n.data.detail||n.nodeKind} · ${n.uid}`))):choices?h('select',{...props,value:graphForm[name]||choices[0]},...choices.map(v=>h('option',{key:v,value:v},dictionaries.en[v]?t(v):v))):h(wide?'textarea':'input',{...props,type:name==='confidence'?'number':undefined,min:name==='confidence'?0:undefined,max:name==='confidence'?1:undefined,step:name==='confidence'?'.01':undefined}));});
            const submit=()=>{const payload={};for(const [name,,,choices] of definitions[entity]){const value=graphForm[name]??(choices?choices[0]:'');if(value!== '')payload[name]=value;}if(entity==='fact')payload.confidence=Number(graphForm.confidence??'.5');if(entity==='finding')payload.reproducibleSteps=String(graphForm.reproducibleSteps||'').split(/\r?\n/).map(s=>s.trim()).filter(Boolean);act(`graph.add_${entity}`,payload);};
            return h(React.Fragment,null,!snapshot.graph?h('div',{className:'cyber-notice',role:'status'},t('graphUnavailable')):null,h('div',{className:'cyber-toolbar'},...['goal','intent','fact','finding','asset','edge'].map(kind=>h('button',{key:kind,type:'button','aria-pressed':entity===kind,className:entity===kind?'primary':'',onClick:()=>{setEntity(kind);setGraphForm({confidence:'0.5',severity:'medium',type:'domain',kind:kind==='edge'?'related':'info'});}},t(kind)))),dataForm(inputs,submit),...['goals','intents','facts','findings','assets','edges'].map(key=>h('div',{className:'cyber-card',key,style:{marginBottom:16}},h('h2',null,t(key),badge(String(graphRows(key).length))),rowsTable(graphRows(key).map(r=>({uid:r.uid,...r.data})),[['uid','label'],...(key==='edges'?[['sourceId','sourceId'],['targetId','targetId'],['kind','kind']]:key==='goals'?[['target','target'],['objective','objective']]:key==='assets'?[['type','type'],['value','value'],['parentId','parentId'],['meta','meta']]:key==='findings'?[['title','titleField'],['severity','severity'],['intentId','intentId'],['description','description'],['reproducibleSteps','reproducibleSteps'],['affectedAssetId','affectedAssetId']]:key==='facts'?[['intentId','intentId'],['kind','kind'],['target','target'],['detail','detail'],['confidence','confidence']]:[['title','titleField'],['sourceId','sourceId'],['detail','detail']])],r=>button('inspection',()=>setAnswer(r))))));
          }
          let content;
          if(tab==='dashboard') content=h(React.Fragment,null,h('div',{className:'cyber-grid'},...['assets','vulnerabilities','tasks','approvals'].map(key=>h('div',{key,className:'cyber-card'},h('span',{className:'cyber-sub'},t(key)),h('div',{className:'cyber-number'},key==='assets'?(snapshot.assets?.length||0)+graphRows('assets').length:key==='vulnerabilities'?(snapshot.vulnerabilities?.length||0)+graphRows('findings').length:key==='approvals'?(snapshot.approvals||[]).filter(r=>r.status==='pending').length:snapshot.tasks?.length||0),h('span',{className:'cyber-sub'},t(key==='approvals'?'pending':'total'))))),h('div',{className:'cyber-split'},severityChart(),h('div',{className:'cyber-card'},h('h2',null,t('exploration')),h('div',{className:'cyber-grid'},...['goals','intents','facts','edges'].map(key=>h('div',{key},h('span',{className:'cyber-sub'},t(key)),h('div',{className:'cyber-number'},graphRows(key).length)))))),h('div',{className:'cyber-card'},h('h2',null,t('tasks')),rowsTable(snapshot.tasks,[['id','label'],['recipe','recipe'],['status','status']])));
          if(tab==='exploration') content=exploration();
          if(tab==='assets') content=h(React.Fragment,null,dataForm([field('type','type',['domain','ip','port','service']),field('value','value')],()=>act('asset.create',{type:form.type,value:form.value})),h('div',{className:'cyber-actions'},button('export',()=>{const blob=new Blob([JSON.stringify(snapshot.assets||[],null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='cyber-assets.json';a.click();URL.revokeObjectURL(url);})),rowsTable(snapshot.assets,[['id','label'],['type','type'],['value','value']],row=>button('remove',()=>{if(window.confirm(t('confirmDelete')))act('asset.delete',{id:row.id});})));
          if(tab==='vulnerabilities') content=h(React.Fragment,null,dataForm([field('title','titleField'),field('severity','severity',['critical','high','medium','low','info']),field('assetId','asset'),field('description','description',null,true)],()=>act('vulnerability.create',{title:form.title,severity:form.severity,assetId:form.assetId?Number(form.assetId):undefined,description:form.description})),rowsTable(snapshot.vulnerabilities,[['id','label'],['title','titleField'],['severity','severity'],['status','status']],row=>h('select',{'aria-label':t('status'),value:row.status,onChange:e=>act('vulnerability.update',{id:row.id,status:e.target.value})},...['open','confirmed','fixed','false_positive'].map(s=>h('option',{key:s,value:s},t(s))))));
          if(tab==='tasks') content=h(React.Fragment,null,dataForm([field('recipe','recipe',(snapshot.recipes||[]).map(r=>r.name)),field('params','params',null,true)],()=>{try{act('task.run',{recipe:form.recipe||snapshot.recipes?.[0]?.name,params:JSON.parse(form.params)});}catch(e){setFailure(e.message);}}),rowsTable(snapshot.tasks,[['id','label'],['recipe','recipe'],['status','status']],row=>h('div',{className:'cyber-actions'},button('result',()=>setAnswer(row)),row.status==='running'?button('cancel',()=>act('task.cancel',{id:row.id})):null)));
          if(tab==='approvals') content=h(React.Fragment,null,h('div',{className:'cyber-card',style:{marginBottom:20}},h('h2',null,t('approvals'),badge('pending')),h('p',{className:'cyber-help'},t('approvalHelp')),h('div',{className:'cyber-grid'},...['pending','approved','rejected'].map(status=>h('div',{key:status},badge(status),h('div',{className:'cyber-number'},(snapshot.approvals||[]).filter(r=>r.status===status).length))))),rowsTable((snapshot.approvals||[]).map(row=>({...row,risk_level:(snapshot.recipes||[]).find(r=>r.name===row.recipe)?.risk_level||'—'})),[['id','label'],['taskId','taskId'],['recipe','recipe'],['risk_level','risk'],['status','status'],['params','params'],['created_at','timestamp']],row=>h('div',{className:'cyber-actions'},button('inspection',()=>setAnswer(row)),row.status==='pending'?h(React.Fragment,null,button('approve',()=>{if(window.confirm(t('approvalDecision')))act('approval.decide',{id:row.id,approved:true});}),button('deny',()=>{if(window.confirm(t('approvalDecision')))act('approval.decide',{id:row.id,approved:false});})):null)));
          if(tab==='audit') content=h(React.Fragment,null,h('div',{className:'cyber-card',style:{marginBottom:20}},h('h2',null,t('audit'),badge(verification?(verification.ok?'ready':'damaged'):'unchecked')),h('p',{className:'cyber-help'},t('auditHelp')),button('verify',async()=>{setVerification(null);const result=await act('audit.verify');if(result)setVerification(result);}),verification?h('div',{className:'cyber-notice cyber-details',role:'status'},h('strong',null,t(verification.ok?'verified':'damaged')),h('p',null,`${t('total')}: ${verification.total} · ${t('brokenAt')}: ${verification.brokenAt??'—'}`),h('p',{className:'cyber-help'},verification.anchored?`${t('anchor')}: ${String(verification.anchored)}`:t('notAnchored'))):null),rowsTable(snapshot.audit,[['seq','label'],['timestamp','timestamp'],['action','action'],['actor','actor'],['prev_hash','prev_hash'],['hash','hash']],row=>button('inspection',()=>setAnswer(row))));
          if(tab==='knowledge') content=h(React.Fragment,null,dataForm([field('title','titleField'),field('text','importText',null,true)],()=>act('knowledge.ingest',{title:form.title,text:form.text})),h('div',{className:'cyber-form'},field('query','query'),button('search',()=>act('knowledge.search',{query:form.query},true))),rowsTable(snapshot.knowledge,[['id','label'],['title','titleField']]));
          if(tab==='chains') content=h(React.Fragment,null,graphView(),h('details',{className:'cyber-card',style:{marginTop:20}},h('summary',null,t('legacyRecords')),dataForm([field('from','from'),field('to','to'),field('label','relation')],()=>act('chain.create',{from:Number(form.from),to:Number(form.to),label:form.label})),rowsTable(snapshot.chains,[['id','label'],['from','from'],['to','to'],['label','relation']])));
          if(tab==='settings') content=h('div',{className:'cyber-card'},h('h2',null,t('settings')),h('p',{className:'cyber-sub'},'DSH profile / SQLite / YAML / SHA-256'),h('p',null,t('webshell')+' — '+t('disabled')),h('p',null,t('c2')+' — '+t('disabled')));
          return h('section',{className:'cyber','aria-label':t('title')},h('style',null,css+extraCss),h('div',{className:'cyber-wrap'},h('header',{className:'cyber-head'},h('div',null,h('h1',null,t('title')),h('div',{className:'cyber-sub'},t('subtitle'))),h('div',{className:'cyber-actions'},badge(busy||!loaded?'syncing':'ready'),button('refresh',()=>act('snapshot')))),h('nav',{className:'cyber-tabs',role:'tablist'},...['dashboard','exploration','assets','vulnerabilities','tasks','chains','knowledge','approvals','audit','settings'].map(key=>h('button',{key,role:'tab','aria-selected':tab===key,onClick:()=>{setTab(key);setAnswer(null);setFilter('');}},t(key)))),failure?h('div',{className:'cyber-notice cyber-error',role:'alert'},failure):null,notice?h('div',{className:'cyber-notice',role:'status'},notice):null,tab!=='settings'?h('input',{'aria-label':t('search'),placeholder:t('search'),value:filter,onChange:e=>setFilter(e.target.value),style:{marginBottom:16,maxWidth:320}}):null,h('div',{role:'tabpanel'},content),answer?h('div',{className:'cyber-card',style:{marginTop:20}},h('div',{className:'cyber-head'},h('h2',null,t('result')),button('cancel',()=>setAnswer(null))),h('pre',null,JSON.stringify(answer,null,2))):null));
        }
        ctx.slots.inject('sidebar.panellist',()=>ctx.slots.register({name:'sidebar.panellist',id:'cyber',order:35,label:()=>t('title')},Icon));
        ctx.slots.inject('main',()=>ctx.slots.register({name:'main',key:'cyber'},Panel));
      }
    };
  }
});
